---
name: 'Python Semantic Release'

description: 'Automatic Semantic Versioning for Python projects'

inputs:
  additional_options:
    description: 'Additional options for the publish command. Example: --noop'
    required: false
  directory:
    description: 'Sub-directory to cd into before running semantic-release'
    default: '.'
    required: false
  github_token:
    description: 'GitHub token used to push release notes and new commits/tags'
    required: true
  pypi_token:
    description: 'PyPI API token'
    required: false
  repository_username:
    description: 'Username with project access to push to Artifact Repository'
    required: false
  repository_password:
    description: 'Password or token to the account specified in repository_username'
    required: false
  git_committer_name:
    description: 'The human name for the “committer” field'
    required: false
  git_committer_email:
    description: 'The email address for the “committer” field'
    required: false
  ssh_public_signing_key:
    description: 'The ssh public key used to sign commits'
    required: false
  ssh_private_signing_key:
    description: 'The ssh private key used to sign commits'
    required: false

outputs:
  published:
    description: ' "True" if new version is published (pushed a new semver tag to repository).'
  published_version:
    description: 'Published semver version. [major].[minor].[patch]'
  published_version_major:
    description: 'Major part of the published semver version.'
  published_version_minor:
    description: 'Minor part of the published semver version.'
  published_version_patch:
    description: 'Patch part of the published semver version.'
  should_bump:
    description: ' "True" if new version will be published.'
  current_version:
    description: 'Current version.'
  current_release_version:
    description: 'Current release version.'
  new_version:
    description: 'New version'

runs:
  using: 'docker'
  image: 'Dockerfile'
